### ISSUE TITLE
Variable orachk_cols is not populated and hence *sqlgen* becomes syntactically invalid

### ISSUE THREAD

**Issue by simonpane** [dbarj/orachksum#2]
The current version seems to have an issue with the "**orachk_cols**" sqlplus variable (testing on 12.1.0.2 and 18.4.0 both non-CDB).

The issue is that **:orachk_cols** is not populated and becomes a NULL string.  Consequently the **sqlgen** files contain invalid SQL such as:

```
CURSOR OBJ IS
SELECT
NULL AS
FROM   CDB_AUDIT_POLICIES
ORDER  BY 1,2,3,4;
```

and:

```
FOR I IN OBJ
LOOP
DBMS_OUTPUT.PUT_LINE(
       QA(I.)
);
END LOOP;
```

Therefore the output package simply contains the following error instead of the actual output:

```
HEADER ERROR
       QA(I.)
            *
ERROR at line 43:
ORA-06550: line 43, column 13:
PLS-00103: Encountered the symbol ")" when expecting one of the following:
<an identifier> <a double-quoted delimited-identifier>
current delete exists prior
The symbol "<an identifier>" was substituted for ")" to continue.
```

The root cause of this error seems to be that the **:orachk_cols** variable is not being properly set.

**Comment by dbarj** [comment]
Hi @simonpane , sorry for **very late** reply on this. Actually I just didn't notice that there was an issue registered and as I haven't received any email.. I've just missed that.

Can you please verify if this issue is still happening for latest version of orachksum and moat369?

Thanks,
RJ

**Comment by dbarj** [comment]
Fixed on last commit.
